# Generated by Django 5.1.2 on 2024-10-19 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutamento', '0002_remove_contact_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curr_academic_formation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recrutamento.academicformation')),
                ('curr_contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recrutamento.contact')),
                ('curr_personal_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recrutamento.personaldata')),
                ('curr_professional_experience', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recrutamento.professionalexperience')),
            ],
        ),
    ]
