# Generated by Django 5.1.2 on 2024-10-27 21:20

import phonenumber_field.modelfields
import recrutamento.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutamento', '0003_curriculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, validators=[recrutamento.models.validate_email]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
